version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: arx-predict-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-arx_predict_db}
      POSTGRES_USER: ${POSTGRES_USER:-arx_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - arx-network-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-arx_user} -d ${POSTGRES_DB:-arx_predict_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: arx-predict-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"  # Bind to localhost only
    volumes:
      - redis_data_prod:/data
    command: redis-server --appendonly yes
    networks:
      - arx-network-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Express Server
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: arx-predict-app-prod
    restart: unless-stopped
    ports:
      - "3001:3001" 
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: ${FRONTEND_URL}
      ABLY_API_KEY: ${ABLY_API_KEY}
      ABLY_APP_ID: ${ABLY_APP_ID}
      HELIUS_API_KEY: ${HELIUS_API_KEY}
      HELIUS_WEBHOOK_SECRET: ${HELIUS_WEBHOOK_SECRET}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      SOLANA_RPC_URL: ${SOLANA_RPC_URL}
      SOLANA_PROGRAM_ID: ${SOLANA_PROGRAM_ID}
      WALLET_PRIVATE_KEY: ${WALLET_PRIVATE_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - arx-network-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: arx-predict-nginx-prod
    restart: unless-stopped
    ports:
      - "9001:443"  # HTTPS on port 9001
      - "9000:80"   # HTTP on port 9000 (optional, for redirects)
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/dokploy/traefik/dynamic/certificates/certificate-index-1080p-driver-oep88h:/etc/ssl/traefik:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - arx-network-prod
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data_prod:
    driver: local
  redis_data_prod:
    driver: local

networks:
  arx-network-prod:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
